In [ ]:
import os
import json
import pandas as pd
import re
import numpy as np


# Connect to Google Drive
import gspread
import gspread_dataframe
from google.oauth2.service_account import Credentials
from google.oauth2 import service_account
from googleapiclient.discovery import build
from gspread_dataframe import set_with_dataframe
from gspread_dataframe import get_as_dataframe

In [ ]:
# 1. Fetch credentials from environment variable
creds_env = os.environ.get("GDRIVE_CREDENTIALS_KC")

if not creds_env:
    raise ValueError("Environment variable 'GDRIVE_CREDENTIALS' was not found.")

creds_json = json.loads(creds_env)

# 2. Define required scopes
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

# 3. Authenticate service account
creds = service_account.Credentials.from_service_account_info(
    creds_json, scopes=scopes
)

# 4. Initialize Google API clients
drive_service = build("drive", "v3", credentials=creds)
sheets_service = build("sheets", "v4", credentials=creds)

gc = gspread.authorize(creds)

print("Google Drive and Sheets services successfully initialized.")

Mounted at /content/drive

In [ ]:
# Open files

# Open organic posts file
influencers_instagram_final = gc.open_by_key('1s9zK9LsAGnkEynPtM_EiPZ44UYhate8QuDZBmu0MjP0')
influencers_instagram_final = influencers_instagram_final.get_worksheet(0)
influencers_instagram_final = get_as_dataframe(influencers_instagram_final)

influencers_tiktok_final = gc.open_by_key('1XumLQUH6ApJPiGuT4OMQQ4o6QG_xW1Nev9qZ2aaKIJ0')
influencers_tiktok_final = influencers_tiktok_final.get_worksheet(0)
influencers_tiktok_final = get_as_dataframe(influencers_tiktok_final)

In [ ]:
# TikTok Organic_ID as string
influencers_tiktok_final['Organic_ID'] = influencers_tiktok_final['Organic_ID'].apply(
    lambda x: f"{x:.0f}" if pd.notna(x) and x != "" else ""
)

In [ ]:
influencers_tiktok_final['Organic_ID']

0      7489491180615470080
1      7489561985940491264
2      7491078442088140800
3      7491824069449420800
4      7491824069449420800
              ...
310    7647345627524844544
311    7637943869375516672
312    7668514054863980544
313    7670347780652681216
314    7670573509705255936
Name: Organic_ID, Length: 315, dtype: object

In [ ]:
influencers_tiktok_final

,url,copy,date_published,platform,format,influencer,Country,Organic_ID,brand,content_type,...,positive_percentage,negative_percentage,neutral_percentage,positive_comments,negative_comments,neutral_comments,er_influencer_baseline,negative_influencer_baseline,Accionable,run_datetime
0,https://www.tiktok.com/@michelle.iman/video/74...,Fuimos al nuevo lanzamiento de @HuggiesArgenti...,2025-04-04,TikTok,Video,michelle.iman,Argentina,7489491180615470080,Huggies,Influencers,...,0.933333,0.066667,0.000000,29.866667,2.133333,0.000000,0.094752,0.210698,No Boost,2026-05-20 18:44:28
1,https://www.tiktok.com/@carotrippar/video/7489...,Que emoción poder contarles que @huggiesarg va...,2025-04-04,TikTok,Video,carotrippar,Argentina,7489561985940491264,Huggies,Influencers,...,0.954198,0.045802,0.000000,165.076336,7.923664,0.000000,0.086580,0.448283,Boost,2026-05-20 18:44:04
2,https://www.tiktok.com/@danielacelis12/video/7...,@huggiesargentina ❤️#TeBancamosBebe,2025-04-08,TikTok,Video,danielacelis12,Argentina,7491078442088140800,Huggies,Influencers,...,0.725490,0.274510,0.000000,346.058824,130.941176,0.000000,0.080986,0.285518,No Boost,2026-05-20 18:40:33
3,https://www.tiktok.com/@agustinbattioni/video/...,Acompáñenme al espectacular evento de @Huggies...,2025-04-10,TikTok,Video,agustinbattioni,Argentina,7491824069449420800,Huggies,Influencers,...,1.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.097070,0.049603,No Boost,2026-05-20 18:40:20
4,https://www.tiktok.com/@agustinbattioni/video/...,Acompáñenme al espectacular evento de @Huggies...,2025-04-10,TikTok,Video,agustinbattioni,Argentina,7491824069449420800,Huggies,Influencers,...,1.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.097070,0.049603,No Boost,2026-05-20 18:40:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,https://www.tiktok.com/@estefaniaacuna/video/7...,Cosas que volvería a comprar como mamá primeri...,2026-06-04,TikTok,Video,estefaniaacuna,Costa Rica,7647345627524844544,Huggies,Influencers,...,1.000000,0.000000,0.000000,7.000000,0.000000,0.000000,0.084962,0.251082,No Boost,2026-08-07 8:41:01
311,https://www.tiktok.com/@kariinacamposs/video/7...,¿Ver para creer? Acompáñenme a hacer este exp...,2026-05-09,TikTok,Video,kariinacamposs,Costa Rica,7637943869375516672,Huggies,Influencers,...,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.077125,0.048128,No Boost,2026-08-07 8:41:09
312,https://www.tiktok.com/@kariinacamposs/video/7...,Cosas que si me han servido en mi maternidad. ...,2026-07-31,TikTok,Video,kariinacamposs,Costa Rica,7668514054863980544,Huggies,Influencers,...,0.625000,0.375000,0.000000,10.000000,6.000000,0.000000,0.077125,0.048128,No Boost,2026-08-07 8:41:17
313,https://www.tiktok.com/@sisoymachis/video/7670...,estamos en mercurio retrógrado o porque todos ...,2026-08-05,TikTok,Video,sisoymachis,Colombia,7670347780652681216,Kotex,Influencers,...,0.522727,0.159091,0.318182,31.363636,9.545455,19.090909,0.135782,0.070111,Review,2026-08-07 8:41:24
314,https://www.tiktok.com/@giulianajimenezl/video...,Llevo MESES posponiendo este proyecto creativo...,2026-08-05,TikTok,Video,giulianajimenezl,Colombia,7670573509705255936,Kotex,Influencers,...,0.781818,0.127273,0.090909,50.036364,8.145455,5.818182,0.071422,0.116162,Review,2026-08-07 8:41:56

In [ ]:
# Append files
influencers_final = pd.concat(
    [influencers_tiktok_final, influencers_instagram_final],
    ignore_index=True,
)

In [ ]:
# Ensure date format
influencers_final['run_datetime'] = pd.to_datetime(influencers_final['run_datetime'], format='mixed').dt.date

In [ ]:
# Save final table
# Open the destination sheets file
sh = gc.open_by_key('1QwqDvUu5SAt6PHKBZWWOATkqzE58pN_XDnzo6LMiYOI')
worksheet = sh.get_worksheet(0)

# Replace old data with new data
set_with_dataframe(worksheet, influencers_final)
print("DataFrame saved successfully!")

DataFrame saved successfully!