In [ ]:
import os
import json
import pandas as pd
import re
import numpy as np


# Connect to Google Drive
import gspread
import gspread_dataframe
from google.oauth2.service_account import Credentials
from google.oauth2 import service_account
from googleapiclient.discovery import build
from gspread_dataframe import set_with_dataframe
from gspread_dataframe import get_as_dataframe

In [ ]:
# 1. Fetch credentials from environment variable
creds_env = os.environ.get("GDRIVE_CREDENTIALS")

if not creds_env:
    raise ValueError("Environment variable 'GDRIVE_CREDENTIALS' was not found.")

creds_json = json.loads(creds_env)

# 2. Define required scopes
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

# 3. Authenticate service account
creds = service_account.Credentials.from_service_account_info(
    creds_json, scopes=scopes
)

# 4. Initialize Google API clients
drive_service = build("drive", "v3", credentials=creds)
sheets_service = build("sheets", "v4", credentials=creds)

gc = gspread.authorize(creds)

print("Google Drive and Sheets services successfully initialized.")

Successfully authenticated using Drive-stored JSON key!

In [ ]:
# Open files

# Open organic posts file
influencers_instagram_final = gc.open_by_key('1s9zK9LsAGnkEynPtM_EiPZ44UYhate8QuDZBmu0MjP0')
influencers_instagram_final = influencers_instagram_final.get_worksheet(0)
influencers_instagram_final = get_as_dataframe(influencers_instagram_final)

influencers_tiktok_final = gc.open_by_key('1XumLQUH6ApJPiGuT4OMQQ4o6QG_xW1Nev9qZ2aaKIJ0')
influencers_tiktok_final = influencers_tiktok_final.get_worksheet(0)
influencers_tiktok_final = get_as_dataframe(influencers_tiktok_final)

In [ ]:
# TikTok Organic_ID as string
influencers_tiktok_final['Organic_ID'] = influencers_tiktok_final['Organic_ID'].apply(
    lambda x: f"{x:.0f}" if pd.notna(x) and x != "" else ""
)

In [ ]:
influencers_tiktok_final['Organic_ID']

0      7489491180615470080
1      7489561985940491264
2      7491078442088140800
3      7491824069449420800
4      7491824069449420800
              ...
303    7632752068721215488
304    7634725781658160128
305    7654612822197947392
306    7630868822517484544
307    7657276171461134336
Name: Organic_ID, Length: 308, dtype: object

In [ ]:
influencers_tiktok_final

,url,copy,date_published,platform,format,influencer,Country,Organic_ID,brand,content_type,...,positive_percentage,negative_percentage,neutral_percentage,positive_comments,negative_comments,neutral_comments,er_influencer_baseline,negative_influencer_baseline,Accionable,run_datetime
0,https://www.tiktok.com/@michelle.iman/video/74...,Fuimos al nuevo lanzamiento de @HuggiesArgenti...,2025-04-04,TikTok,Video,michelle.iman,Argentina,7489491180615470080,Huggies,Influencers,...,0.933333,0.066667,0.0,29.866667,2.133333,0.0,0.094752,0.210698,No Boost,2026-05-20 18:44:28
1,https://www.tiktok.com/@carotrippar/video/7489...,Que emoción poder contarles que @huggiesarg va...,2025-04-04,TikTok,Video,carotrippar,Argentina,7489561985940491264,Huggies,Influencers,...,0.954198,0.045802,0.0,165.076336,7.923664,0.0,0.086580,0.448283,Boost,2026-05-20 18:44:04
2,https://www.tiktok.com/@danielacelis12/video/7...,@huggiesargentina ❤️#TeBancamosBebe,2025-04-08,TikTok,Video,danielacelis12,Argentina,7491078442088140800,Huggies,Influencers,...,0.725490,0.274510,0.0,346.058824,130.941176,0.0,0.080986,0.285518,No Boost,2026-05-20 18:40:33
3,https://www.tiktok.com/@agustinbattioni/video/...,Acompáñenme al espectacular evento de @Huggies...,2025-04-10,TikTok,Video,agustinbattioni,Argentina,7491824069449420800,Huggies,Influencers,...,1.000000,0.000000,0.0,3.000000,0.000000,0.0,0.097070,0.049603,No Boost,2026-05-20 18:40:20
4,https://www.tiktok.com/@agustinbattioni/video/...,Acompáñenme al espectacular evento de @Huggies...,2025-04-10,TikTok,Video,agustinbattioni,Argentina,7491824069449420800,Huggies,Influencers,...,1.000000,0.000000,0.0,3.000000,0.000000,0.0,0.097070,0.049603,No Boost,2026-05-20 18:40:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,https://www.tiktok.com/@sheirismontero/video/7...,Mito o verdad edición pañales de bebé ✨✨ Yo en...,2026-04-25,TikTok,Video,sheirismontero,Costa Rica,7632752068721215488,Huggies,Influencers,...,NaN,NaN,NaN,NaN,NaN,NaN,0.066197,0.050336,No Boost,2026-07-30 19:50:15
304,https://www.tiktok.com/@miche_naranjo07/video/...,"No importa que tanto juegue, brinque o corra F...",2026-05-01,TikTok,Video,miche_naranjo07,Costa Rica,7634725781658160128,Huggies,Influencers,...,1.000000,0.000000,0.0,1.000000,0.000000,0.0,0.111578,0.161290,No Boost,2026-07-30 19:50:24
305,https://www.tiktok.com/@mapabruna/video/765461...,"Y llegamos a la etapa de la exploración, jugar...",2026-06-23,TikTok,Video,mapabruna,Costa Rica,7654612822197947392,Huggies,Influencers,...,0.700000,0.100000,0.2,23.800000,3.400000,6.8,0.034373,0.086957,No Boost,2026-07-30 19:51:00
306,https://www.tiktok.com/@nela_valverde/video/76...,Mamitas si van a tener bebé o están con recién...,2026-04-20,TikTok,Video,nela_valverde,Costa Rica,7630868822517484544,Huggies,Influencers,...,1.000000,0.000000,0.0,14.000000,0.000000,0.0,0.015717,0.000000,Boost,2026-07-30 19:51:23
307,https://www.tiktok.com/@nela_valverde/video/76...,En cada sonrisa hay un papá que quiere lo mejo...,2026-06-30,TikTok,Video,nela_valverde,Costa Rica,7657276171461134336,Huggies,Influencers,...,1.000000,0.000000,0.0,8.000000,0.000000,0.0,0.015717,0.000000,No Boost,2026-07-30 19:51:34

In [ ]:
# Append files
influencers_final = pd.concat(
    [influencers_tiktok_final, influencers_instagram_final],
    ignore_index=True,
)

In [ ]:
# Save final table
# Open the destination sheets file
sh = gc.open_by_key('1wNrREJ4OEQfjMIdok_rSx-vYG8f-He77XTlScik9hSc')
worksheet = sh.get_worksheet(0)

# Replace old data with new data
set_with_dataframe(worksheet, influencers_final)
print("DataFrame saved successfully!")

DataFrame saved successfully!